package br.com.ifgoiano.usuario;
// Generated 09/12/2019 23:30:23 by Hibernate Tools 4.3.1

//import java.util.HashSet;
//import java.util.Set;
import java.io.Serializable;
//import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
//import javax.persistence.Temporal;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
public class Usuarios implements Serializable {

   // private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue
    private Integer id;
    private boolean ativo;
    @org.hibernate.annotations.NaturalId
    private String email;
    private String nome;
    private String senha;
    private String idioma;
     
    private String rua;
    private String cep;
    private String numero;
    private String cidade;
    private String estado;

       
    
    @ElementCollection(targetClass = String.class)
    @JoinTable(name = "usuario_permissao", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"id_usuario", "permissao"})},
    joinColumns = @JoinColumn(name = "id_usuario"))
    @Column(name = "permissao", length = 50)
    private Set<String> permissao = new HashSet<String>();

    public String getRua() {
        return rua;
    }

    public void setRua(String rua) {
        this.rua = rua;
    }

    public String getCep() {
        return cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getCidade() {
        return cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public boolean isAtivo() {
        return this.ativo;
    }

    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
public String getIdioma() {
		return idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public Set<String> getPermissao() {
        return permissao;
    }

    public void setPermissao(Set<String> permissao) {
        this.permissao = permissao;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (ativo ? 1231 : 1237);
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((email == null) ? 0 : email.hashCode());
        result = prime * result + ((idioma == null) ? 0 : idioma.hashCode());
        result = prime * result + ((nome == null) ? 0 : nome.hashCode());
        result = prime * result + ((permissao == null) ? 0 : permissao.hashCode());
        result = prime * result + ((senha == null) ? 0 : senha.hashCode());
        /*result = prime * result + ((rua == null) ? 0 : rua.hashCode());
        result = prime * result + ((cidade == null) ? 0 : cidade.hashCode());
        result = prime * result + ((cep == null) ? 0 : cep.hashCode());
        result = prime * result + ((numero == null) ? 0 : numero.hashCode());
        result = prime * result + ((estado == null) ? 0 : estado.hashCode());*/
      
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Usuarios other = (Usuarios) obj;
        if (ativo != other.ativo) {
            return false;
        }

        if (!Objects.equals(this.email, other.email)) {
            return false;
        }
        if (email == null) {
            if (other.email != null) {
                return false;
            }
        } else if (!email.equals(other.email)) {
            return false;
        }

        if (email == null) {
            if (other.email != null) {
                return false;
            }
        } else if (!email.equals(other.email)) {
            return false;
        }

        if (nome == null) {
            if (other.nome != null) {
                return false;
            }
        } else if (!nome.equals(other.nome)) {
            return false;
        }
        if (rua == null) {
            if (other.rua != null) {
                return false;
            }
        } else if (!rua.equals(other.rua)) {
            return false;
        }
        if (cidade == null) {
            if (other.cidade != null) {
                return false;
            }
        } else if (!cidade.equals(other.cidade)) {
            return false;
        }
        if (estado == null) {
            if (other.estado != null) {
                return false;
            }
        } else if (!estado.equals(other.estado)) {
            return false;
        }
        if (numero == null) {
            if (other.numero != null) {
                return false;
            }
        } else if (!numero.equals(other.numero)) {
            return false;
        }
        if (cep == null) {
            if (other.cep != null) {
                return false;
            }
        } else if (!cep.equals(other.cep)) {
            return false;
        }
if (idioma == null) {
			if (other.idioma != null)
				return false;
		} else if (!idioma.equals(other.idioma))
			return false;
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        if (permissao == null) {
            if (other.permissao != null) {
                return false;
            }
        } 
        else if (!permissao.equals(other.permissao)) {
            if (senha == null) {
                if (other.senha != null) {
                    return false;
                }
            } else if (!senha.equals(other.senha)) {
                return false;
            }
        }
              
        return true;

    }

}



